[package]
name = "traitable-core"
version.workspace = true
edition.workspace = true

[dependencies]
basic-toml = "0.1"
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2.0", features = ["full"]}
thiserror = "1.0"